//! Sound effects. SFX (mp3) live in `assets/audio/` (generated by
//! `tools/gen_sfx.sh` via ElevenLabs). Gameplay systems emit `SfxEvent`s; a single
//! `play_sfx` system spawns one-shot audio entities, with a per-kind throttle so
//! rapid events (deaths/explosions) don't pile up into noise.

use bevy::audio::{PlaybackMode, Volume};
use bevy::prelude::*;
use std::collections::HashMap;

#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub enum Sound {
    Build,
    Shoot,
    Hit,
    Explosion,
    Death,
    Meteor,
    Freeze,
    Gold,
    Wave,
    Victory,
    Defeat,
    Click,
    // extra SFX (gen_sfx_extra.sh)
    Upgrade,
    Sell,
    Summon,
    Raise,
    Laser,
    Poison,
    Chain,
    Boss,
    Combo,
    NoGold,
    WaveClear,
    Curse,
}

impl Sound {
    fn file(self) -> &'static str {
        use Sound::*;
        match self {
            Build => "build",
            Shoot => "shoot",
            Hit => "hit",
            Explosion => "explosion",
            Death => "death",
            Meteor => "meteor",
            Freeze => "freeze",
            Gold => "gold",
            Wave => "wave",
            Victory => "victory",
            Defeat => "defeat",
            Click => "click",
            Upgrade => "upgrade",
            Sell => "sell",
            Summon => "summon",
            Raise => "raise",
            Laser => "laser",
            Poison => "poison",
            Chain => "chain",
            Boss => "boss",
            Combo => "combo",
            NoGold => "nogold",
            WaveClear => "waveclear",
            Curse => "curse",
        }
    }
    /// Minimum seconds between plays of this sound (throttle spammy ones).
    fn min_gap(self) -> f32 {
        match self {
            Sound::Death | Sound::Explosion | Sound::Hit => 0.06,
            Sound::Shoot | Sound::Laser | Sound::Chain | Sound::Poison => 0.05,
            Sound::Summon | Sound::Raise | Sound::Curse => 0.18,
            Sound::Combo => 0.12,
            _ => 0.0,
        }
    }
    fn volume(self) -> f32 {
        match self {
            Sound::Death | Sound::Hit | Sound::Shoot => 0.4,
            Sound::Explosion => 0.55,
            Sound::Victory | Sound::Defeat => 0.8,
            _ => 0.6,
        }
    }
}

/// Player-adjustable master volume (0.0–1.0), persisted across sessions. Scales
/// both SFX and the looping BGM. Cycled in discrete steps from the settings panel.
#[derive(Resource)]
pub struct AudioSettings {
    pub master: f32,
}

impl Default for AudioSettings {
    fn default() -> Self {
        Self::load()
    }
}

impl AudioSettings {
    /// Discrete steps the settings button cycles through.
    const STEPS: [f32; 5] = [0.0, 0.25, 0.5, 0.75, 1.0];

    pub fn load() -> Self {
        let master = load_volume()
            .trim()
            .parse::<f32>()
            .ok()
            .map(|v| v.clamp(0.0, 1.0))
            .unwrap_or(1.0);
        Self { master }
    }

    pub fn cycle(&mut self) {
        // Advance to the next step above the current value (wrapping).
        let next = Self::STEPS
            .iter()
            .copied()
            .find(|&s| s > self.master + 0.01)
            .unwrap_or(Self::STEPS[0]);
        self.master = next;
        save_volume(&format!("{:.2}", self.master));
    }

    /// 0–100 for display.
    pub fn percent(&self) -> u32 {
        (self.master * 100.0).round() as u32
    }
}

#[derive(Resource)]
pub struct Sfx {
    handles: HashMap<Sound, Handle<AudioSource>>,
    last: HashMap<Sound, f32>,
}

impl Sfx {
    pub fn handle(&self, s: Sound) -> Handle<AudioSource> {
        self.handles[&s].clone()
    }
}

/// One-shot play request.
#[derive(Message)]
pub struct SfxEvent(pub Sound);

const ALL: [Sound; 24] = [
    Sound::Build,
    Sound::Shoot,
    Sound::Hit,
    Sound::Explosion,
    Sound::Death,
    Sound::Meteor,
    Sound::Freeze,
    Sound::Gold,
    Sound::Wave,
    Sound::Victory,
    Sound::Defeat,
    Sound::Click,
    Sound::Upgrade,
    Sound::Sell,
    Sound::Summon,
    Sound::Raise,
    Sound::Laser,
    Sound::Poison,
    Sound::Chain,
    Sound::Boss,
    Sound::Combo,
    Sound::NoGold,
    Sound::WaveClear,
    Sound::Curse,
];

/// Start the looping background music (Suno-generated, `assets/audio/bgm.mp3`).
/// On the web it begins once the browser resumes audio after the first gesture.
pub fn start_bgm(mut commands: Commands, assets: Res<AssetServer>, audio: Res<AudioSettings>) {
    commands.spawn((
        AudioPlayer(assets.load::<AudioSource>("audio/bgm.mp3")),
        PlaybackSettings {
            mode: PlaybackMode::Loop,
            volume: Volume::Linear(BGM_BASE * audio.master),
            ..default()
        },
        Bgm,
    ));
}

pub fn load_sfx(mut commands: Commands, assets: Res<AssetServer>) {
    let mut handles = HashMap::new();
    for s in ALL {
        handles.insert(s, assets.load(format!("audio/{}.mp3", s.file())));
    }
    commands.insert_resource(Sfx {
        handles,
        last: HashMap::new(),
    });
}

/// Spawn a one-shot audio entity for a sound (despawns when finished). `master`
/// is the player's master-volume multiplier (0–1).
pub fn play_oneshot(commands: &mut Commands, sfx: &Sfx, s: Sound, master: f32) {
    commands.spawn((
        AudioPlayer(sfx.handle(s)),
        PlaybackSettings {
            mode: PlaybackMode::Despawn,
            volume: Volume::Linear(s.volume() * master),
            ..default()
        },
    ));
}

pub fn play_sfx(
    mut commands: Commands,
    time: Res<Time>,
    mut sfx: ResMut<Sfx>,
    audio: Res<AudioSettings>,
    mut events: MessageReader<SfxEvent>,
) {
    let now = time.elapsed_secs();
    for SfxEvent(s) in events.read() {
        let last = sfx.last.get(s).copied().unwrap_or(-100.0);
        if now - last < s.min_gap() {
            continue;
        }
        sfx.last.insert(*s, now);
        play_oneshot(&mut commands, &sfx, *s, audio.master);
    }
}

/// Marker for the looping BGM entity so its volume can be re-scaled live.
#[derive(Component)]
pub struct Bgm;

const BGM_BASE: f32 = 0.32;

/// Re-apply master volume to the BGM sink whenever the setting changes.
pub fn apply_master_volume(audio: Res<AudioSettings>, mut sinks: Query<&mut AudioSink, With<Bgm>>) {
    if !audio.is_changed() {
        return;
    }
    for mut sink in &mut sinks {
        sink.set_volume(Volume::Linear(BGM_BASE * audio.master));
    }
}

// ---- persistence ----

#[cfg(target_arch = "wasm32")]
#[wasm_bindgen::prelude::wasm_bindgen(inline_js = r#"
export function load_volume() {
  try { return globalThis.localStorage?.getItem('protect_carrot_volume') || ''; }
  catch (_) { return ''; }
}
export function save_volume(value) {
  try { globalThis.localStorage?.setItem('protect_carrot_volume', value); }
  catch (_) {}
}
"#)]
extern "C" {
    #[wasm_bindgen::prelude::wasm_bindgen(js_name = load_volume)]
    fn load_volume_js() -> String;
    #[wasm_bindgen::prelude::wasm_bindgen(js_name = save_volume)]
    fn save_volume_js(value: &str);
}

#[cfg(target_arch = "wasm32")]
fn load_volume() -> String {
    load_volume_js()
}

#[cfg(target_arch = "wasm32")]
fn save_volume(value: &str) {
    save_volume_js(value);
}

#[cfg(not(target_arch = "wasm32"))]
fn load_volume() -> String {
    std::fs::read_to_string("tmp/volume.txt").unwrap_or_default()
}

#[cfg(not(target_arch = "wasm32"))]
fn save_volume(value: &str) {
    let _ = std::fs::create_dir_all("tmp");
    let _ = std::fs::write("tmp/volume.txt", value);
}
