//! Sprite textures for towers and enemies, loaded from `assets/sprites/`.
//!
//! The PNGs are generated by `tools/gen_sprites.py`. Loading goes through the
//! `AssetServer` (async); handles are stored in a `Resource` keyed by kind.

use crate::data::{EnemyKind, TowerKind};
use crate::equipment::Equipment;
use crate::hero::{HeroLoadout, HeroWeapon, Race};
use crate::meta::Ability;
use crate::monster::{BossSkill, MONSTER_SPECIES};
use bevy::prelude::*;
use std::collections::HashMap;

#[derive(Resource)]
pub struct Sprites {
    pub towers: HashMap<TowerKind, Handle<Image>>,
    pub enemies: HashMap<EnemyKind, Handle<Image>>,
    pub species: HashMap<usize, Handle<Image>>,
    pub equipment: HashMap<Equipment, Handle<Image>>,
    /// 英雄装备图标：按纸娃娃 fragment id 索引——与娃娃身上穿的是同一套
    /// AI 道具图，保证「背包图 = 角色实际穿戴」。
    pub hero_gear_icons: HashMap<u32, Handle<Image>>,
    /// 英雄武器实物图（同纸娃娃武器图层），用于已装备武器槽。
    pub hero_weapon_props: HashMap<crate::hero_gear::HeroWeaponKind, Handle<Image>>,
    /// Active-ability icons (meteor / freeze / gold rush).
    pub abilities: HashMap<Ability, Handle<Image>>,
    /// Talent icons, keyed by "damage" / "range" / "speed".
    pub talents: HashMap<&'static str, Handle<Image>>,
    /// Hero weapon portraits keyed by weapon.
    pub heroes: HashMap<HeroWeapon, Handle<Image>>,
    /// Hero active skill icons keyed by weapon.
    pub hero_skills: HashMap<HeroWeapon, Handle<Image>>,
    /// Hero talent icons keyed by (weapon, talent index).
    pub hero_talents: HashMap<(HeroWeapon, usize), Handle<Image>>,
    /// Independent allied creature sprite used by the summon-staff active skill.
    pub mythic_summon: Handle<Image>,
    /// Boss portraits keyed by the boss's signature skill.
    pub bosses: HashMap<BossSkill, Handle<Image>>,
    /// The defended carrot (level goal) and the enemy spawn portal. The carrot has
    /// healthy/hurt/critical states swapped by remaining lives.
    pub carrot: Handle<Image>,
    pub carrot_hurt: Handle<Image>,
    pub carrot_crit: Handle<Image>,
    pub spawn_portal: Handle<Image>,
    /// Melee slash effect (physical) and a toxic variant (poison melee).
    pub slash: Handle<Image>,
    pub slash_poison: Handle<Image>,
    /// Race face icons (human / elf / orc) for the visual hero selector.
    pub races: HashMap<Race, Handle<Image>>,
    /// Small HUD icons keyed by name (coin / heart / wave / intel) replacing text.
    pub ui: HashMap<&'static str, Handle<Image>>,
}

/// Startup: kick off loading every tower/enemy sprite. Handles are returned
/// immediately; the images stream in asynchronously (well before they're needed).
/// Build the sprite handle table. Called *before* `app.run()` (not as a Startup
/// system) so the resource exists before the initial `OnEnter(Menu)` reads it —
/// Startup loses the race with the first state transition (see the font in main.rs).
pub fn build_sprites(assets: &AssetServer) -> Sprites {
    // 英雄装备/武器图标（与 assets/paperdoll 图层同源的 AI 道具图）。
    let gear_frag_files: [(u32, &str); 15] = [
        (200, "gear_vow_plate"),
        (201, "gear_starweave_robe"),
        (202, "gear_windrunner_cloak"),
        (210, "gear_thunder_charm"),
        (211, "gear_saint_bell"),
        (212, "gear_night_mask"),
        (220, "gear_forge_gauntlet"),
        (221, "gear_warden_scope"),
        (222, "gear_carrot_halo"),
        (230, "gear_wayfarer_boots"),
        (231, "gear_bloodstep_greaves"),
        (232, "gear_starpath_sandals"),
        (233, "gear_engineer_treads"),
        (234, "gear_summoner_greaves"),
        (235, "gear_carrot_wings"),
    ];
    let mut hero_gear_icons = HashMap::new();
    for (frag, file) in gear_frag_files {
        hero_gear_icons.insert(
            frag,
            assets.load(format!("sprites/hero_gear/{file}.webp")),
        );
    }
    use crate::hero_gear::HeroWeaponKind as WK;
    let weapon_prop_files: [(WK, &str); 9] = [
        (WK::Sword, "weapon_sword"),
        (WK::Staff, "weapon_staff"),
        (WK::Bow, "weapon_bow"),
        (WK::Shield, "weapon_shield"),
        (WK::StormOrb, "weapon_storm_orb"),
        (WK::SentryBow, "weapon_sentry_bow"),
        (WK::Dagger, "weapon_dagger"),
        (WK::SummonStaff, "weapon_censer"),
        (WK::Hammer, "weapon_hammer"),
    ];
    let mut hero_weapon_props = HashMap::new();
    for (kind, file) in weapon_prop_files {
        hero_weapon_props.insert(
            kind,
            assets.load(format!("sprites/hero_gear/{file}.webp")),
        );
    }

    let mut towers = HashMap::new();
    for k in TowerKind::ALL {
        towers.insert(
            k,
            assets.load(format!("sprites/towers/{}.webp", k.sprite_name())),
        );
    }
    let mut enemies = HashMap::new();
    for k in EnemyKind::ALL {
        enemies.insert(
            k,
            assets.load(format!("sprites/enemies/{}.webp", k.sprite_name())),
        );
    }
    let mut species = HashMap::new();
    for s in MONSTER_SPECIES {
        let sprite_id = if s.id > 99 { 99 } else { s.id };
        species.insert(
            s.id,
            assets.load(format!("sprites/species/{:03}.webp", sprite_id)),
        );
    }
    let mut equipment = HashMap::new();
    for item in Equipment::ALL {
        equipment.insert(
            item,
            assets.load(format!("sprites/equipment/{}.webp", item.sprite_name())),
        );
    }
    let mut abilities = HashMap::new();
    for (ab, file) in [
        (Ability::Meteor, "meteor"),
        (Ability::Freeze, "freeze"),
        (Ability::GoldRush, "goldrush"),
    ] {
        abilities.insert(ab, assets.load(format!("sprites/abilities/{}.webp", file)));
    }
    let mut talents = HashMap::new();
    for key in ["damage", "range", "speed"] {
        talents.insert(key, assets.load(format!("sprites/talents/{}.webp", key)));
    }
    let mut heroes = HashMap::new();
    let mut hero_skills = HashMap::new();
    let mut hero_talents = HashMap::new();
    for weapon in HeroWeapon::ALL {
        heroes.insert(
            weapon,
            assets.load(format!("sprites/heroes/{}.webp", weapon.sprite_name())),
        );
        hero_skills.insert(
            weapon,
            assets.load(format!(
                "sprites/hero_skills/{}.webp",
                weapon.skill_sprite_name()
            )),
        );
        for talent in 0..HeroLoadout::TALENT_SLOTS {
            hero_talents.insert(
                (weapon, talent),
                assets.load(format!(
                    "sprites/hero_talents/{}.webp",
                    weapon.talent_sprite_name(talent)
                )),
            );
        }
    }
    let mut bosses = HashMap::new();
    for skill in BossSkill::ALL {
        if let Some(name) = skill.portrait_name() {
            bosses.insert(skill, assets.load(format!("sprites/bosses/{}.webp", name)));
        }
    }
    Sprites {
        towers,
        enemies,
        species,
        equipment,
        hero_gear_icons,
        hero_weapon_props,
        abilities,
        talents,
        heroes,
        hero_skills,
        hero_talents,
        mythic_summon: assets.load("sprites/summons/mythic_summon.webp"),
        bosses,
        carrot: assets.load("sprites/carrot.webp"),
        carrot_hurt: assets.load("sprites/carrot_hurt.webp"),
        carrot_crit: assets.load("sprites/carrot_crit.webp"),
        spawn_portal: assets.load("sprites/portal.webp"),
        slash: assets.load("sprites/slash.webp"),
        slash_poison: assets.load("sprites/slash_poison.webp"),
        races: Race::ALL
            .into_iter()
            .map(|r| {
                let n = match r {
                    Race::Human => "human",
                    Race::Elf => "elf",
                    Race::Orc => "orc",
                };
                (r, assets.load(format!("sprites/races/{}.webp", n)))
            })
            .collect(),
        ui: [
            "coin",
            "heart",
            "wave",
            "intel",
            "cat_attack",
            "cat_control",
            "cat_support",
            "cat_special",
            "sec_skill",
            "sec_talent",
            "diff_easy",
            "diff_normal",
            "diff_hard",
            "st_damage",
            "st_range",
            "st_armor",
            "st_speed",
            "st_dps",
            "ctrl_start",
            "ctrl_auto",
            "ctrl_pause",
            "ctrl_speed",
            "circle",
            "meteor_fx",
            "nav_bestiary",
            "nav_towers",
            "nav_armory",
            "nav_milestones",
            "nav_dossier",
            "nav_hero",
            "ic_gear",
            "ic_skull",
            "ic_star",
            "ic_flag",
            "ic_lock",
        ]
        .into_iter()
        .map(|n| (n, assets.load(format!("sprites/ui/{}.webp", n))))
        .collect(),
    }
}
